# This file can be used to install module dependencies for unit testing
# See https://github.com/puppetlabs/puppetlabs_spec_helper#using-fixtures for details
---
fixtures:
  symlinks:
    cis_security_hardening: "#{source_dir}"
  repositories:
    provision: 
      repo: 'https://github.com/puppetlabs/provision.git'
      branch: 'main'
  forge_modules:
    stdlib:                     "puppetlabs/stdlib"
    concat:                     "puppetlabs/concat"
    kmod:                       "puppet/kmod"
    echo:                       "ipcrm/echo"
    sysctl:                     "fiddyspence/sysctl"
    augeasproviders_pam:        "puppet/augeasproviders_pam"
    augeasproviders_core:       "puppet/augeasproviders_core"
    augeasproviders_grub:       "puppet/augeasproviders_grub"
    augeas_core:                "puppetlabs/augeas_core"
    logrotate:                  "puppet/logrotate"
    ntp:                        "puppetlabs/ntp"
    chrony:                     "puppet/chrony"
    firewall:                   "puppetlabs/firewall"
    reboot:                     "puppetlabs/reboot"
    inifile:                    "puppetlabs/inifile"
    puppet_agent:               "puppetlabs/puppet_agent"
    facts:                      "puppetlabs/facts"
    recursive_file_permissions: "npwalker/recursive_file_permissions"
