# This file can be used to install module dependencies for unit testing
# See https://github.com/puppetlabs/puppetlabs_spec_helper#using-fixtures for details
---
fixtures:
  symlinks:
    cis_security_hardening: "#{source_dir}"
  repositories:
    provision: 
      repo: 'https://github.com/puppetlabs/provision.git'
      branch: 'main'
  forge_modules:
    stdlib:
      repo: "puppetlabs/stdlib"
      ref: "6.0"
    concat:
      repo: "puppetlabs/concat"
      ref: "5.3.0"
    kmod:
      repo: "camptocamp/kmod"
      ref: "2.3.1"
    augeas:
      repo: "camptocamp/augeas"
      ref: "1.8.0"
    echo:
      repo: "ipcrm/echo"
      ref: "0.1.6"
    augeasproviders:
      repo: "herculesteam/augeasproviders"
      ref: "2.2.1"
    augeasprovider_pam:
      repo: "herculesteam/augeasproviders_pam"
      ref: "2.2.1"
    augeasprovider_core:
      repo: "herculesteam/augeasproviders_core"
      ref: "2.5.0"
    sysctl:
      repo: "herculesteam/augeasproviders_sysctl"
      ref: "2.3.1"
    augeasprovider_grub:
      repo: "herculesteam/augeasproviders_grub"
      ref: "3.1.0"
    augeasprovider_shellvar:
      repo: "herculesteam/augeasproviders_shellvar"
      ref: "3.1.0"
    augeasprovider_mounttab:
      repo: "herculesteam/augeasproviders_mounttab"
      ref: "2.1.1"
    syslogng:
      repo: "purplehazech/syslogng"
      ref: "0.7.1"
    rsyslog:
      repo: "puppet/rsyslog"
      ref: "3.3.0"
    logrotate:
      repo: "puppet/logrotate"
      ref: "4.0.0"
    ntp:
      repo: "puppetlabs/ntp"
      ref: "8.0.0"
    chrony:
      repo: "jorten/chrony"
      ref: "0.3.0"
    augeas_core:
      repo: "puppetlabs/augeas_core"
      ref: "1.0.5"
    firewall:
      repo: "puppetlabs/firewall"
      ref: "2.2.0"
    mount_providers:
      repo: "puppetlabs/mount_providers"
      ref: "2.0.1"
    reboot:
      repo: "puppetlabs/reboot"
      ref: "2.3.0"
    puppet_agent:
      repo: "puppetlabs/puppet_agent"
      ref: "3.0.2"
    facts:
      repo: "puppetlabs/facts"
      ref: "1.0.0"
    inifile:
      repo: "puppetlabs/inifile"
      ref: "4.1.0"
    apt:
      repo: "puppetlabs/apt"
      ref: "7.3.0"
    registry:
      repo: "puppetlabs/registry"
      ref: "3.1.0"
    autofs:
      repo: "puppet/autofs"
      ref: "5.0.1"
    fstab:
      repo: "AlexCline/fstab"
      ref: "0.5.4"
