---
Gemfile:
  optional:
    ':system_tests':
      - gem: 'serverspec'
      - gem: 'hiera-puppet-helper'
    ':development':
      - gem: 'puppet-strings'
      - gem: 'puppet_litmus'
        ref: '~> 0.34.1'
      - gem: 'puppet-lint-security-plugins'

spec/spec_helper.rb:
  mock_with: ':rspec'
  spec_overrides:
    - 'RSpec.configure do |c|'
    - "  c.hiera_config = File.expand_path(File.join(File.dirname(__FILE__), '/fixtures/hiera/hiera.yaml'))"
    - "  c.after(:suite) do"
    - "    RSpec::Puppet::Coverage.report!(80)"
    - "  end"
    - "end"

".rubocop.yml":
  default_configs:
    inherit_from: ".rubocop_todo.yml"
    require:
    - rubocop-rspec

appveyor.yml:
  delete: true

.gitlab-ci.yml:
  delete: true
